Exclude leading zeroes from the dummy version string
Exclude leading zeroes from the dummy version string so the compiler
does not report the dummy version string as comprised of malformed
octals. Alleviates the following compilation error:

error: invalid digit "8" in octal constant