Fixed the initial build errors including but not limited to:
error: invalid conversion from ‘QEvent*’ to ‘QEnterEvent*’
error: using typedef-name ‘using QStringList = class QList<QString>’ after ‘class’
error: ‘void QtCodeField::enterEvent(QEvent*)’ marked ‘override’, but does not override
error: no declaration matches ‘void QtHistoryItem::enterEvent(QEnterEvent*)’
error: ‘class QStyleOption’ has no member named ‘init’
error: ‘class QImage’ has no member named ‘mirrored’
error: ‘stateChanged’ is not a member of ‘QCheckBox’
error: ‘QRegExp’ was not declared in this scope
error: ‘class QRegularExpression’ has no member named ‘indexIn’
error: ‘class QRegularExpression’ has no member named ‘cap’
fatal error: boost/asio/io_service.hpp: No such file or directory
error: ‘io_service’ is not a member of ‘boost::asio’; did you mean ‘use_service’?
error: ‘async_pipe’ is not a member of ‘boost::process’
error: ‘child’ is not a member of ‘boost::process’
error: expected primary-expression before ‘env’
error: ‘args’ is not a member of ‘boost::process’
error: ‘std_in’ is not a member of ‘boost::process’
error: ‘std_out’ is not a member of ‘boost::process’
error: ‘std_err’ is not a member of ‘boost::process’
error: no matching function for call to ‘safely_wait_for(std::__shared_ptr_access<boost::process::v2::basic_process<>, __gnu_cxx::_S_atomic, false, false>::element_type&, std::chrono::milliseconds)’
error: ‘child’ is not a member of ‘boost::process’
error: ‘class QMouseEvent’ has no member named ‘globalPos’; did you mean ‘globalPosition’?
error: ‘stateChanged’ is not a member of ‘QCheckBox’
error: invalid user-defined conversion from ‘const wchar_t’ to ‘const QString&’
error: ‘class QMouseEvent’ has no member named ‘x’
error: ‘virtual void QtBookmark::enterEvent(QEvent*)’ marked ‘override’, but does not override
error: ‘boost::filesystem::symlink_option’ has not been declared
error: ‘class boost::filesystem::recursive_directory_iterator’ has no member named ‘no_push’
error: ‘boost::filesystem::symlink_option’ has not been declared
error: ‘copy_directory’ is not a member of ‘boost::filesystem’; did you mean ‘is_directory’?
error: ‘QRegExp’ does not name a type
error: ‘QRegExp’ was not declared in this scope
error: ‘class QRegularExpression’ has no member named ‘indexIn’
error: ‘class QRegularExpression’ has no member named ‘matchedLength’
error: ‘class QRegularExpression’ has no member named ‘capturedTexts’
error: no matching function for call to ‘QMenu::addAction(QString, QtMainWindow*, void (QtMainWindow::*)(), QKeySequence::StandardKey)’
error: no matching function for call to ‘QMenu::addAction(QString, QCoreApplication*, void (*)(), QKeySequence::StandardKey)’
error: use of deleted function ‘constexpr void Qt::operator+(QFlags<Modifier>::enum_type, int)’
error: use of deleted function ‘constexpr void Qt::operator+(QFlags<Modifier>::enum_type, QFlags<Modifier>::enum_type)’
error: no matching function for call to ‘QMenu::addAction(QString, QtMainWindow*, void (QtMainWindow::*)(), QKeySequence::StandardKey)’
error: ‘AA_EnableHighDpiScaling’ is not a member of ‘Qt’
error: ‘AA_UseHighDpiPixmaps’ is not a member of ‘Qt’

[NOTE]: Most, if not all, of the compilation errors are the result of the upgrade to Boost 1.91.0 and Qt 6.11.0.